### ISSUE TITLE
v0.1.2 - Plugin does not load

### ISSUE THREAD

**Issue by ilayshp** [mcneel/CyclesForRhino#1]
Hi
v0.1.2 of plugin does not load. Installer does not create registry entry for this version ( and early v0.9)

**Comment by jesterKing** [comment]
I just installed v0.1.2 from the RHI file in the latest Rhino WIP release. After install I see:

![image](https://cloud.githubusercontent.com/assets/87916/24075146/b2930b0a-0c1e-11e7-9b90-acfd433d7b27.png)

Is this not what you see?

**Comment by jesterKing** [comment]
Rhino WIP version tested with: 6.0.17073.13071, 17/03/14

**Comment by ilayshp** [comment]
Hello Nathan
yes, i test it with 6.0.17073.13071
I remember that 0.7-0.8 wrote to registry path. Only 0.9 and next version was starting that.
After installing, start up rhino, rhino does not load plugin(message appear that can not load). After all, i manually load rhp file and turn on check at Enable in plugins settings. Then it start normally.

**Comment by jesterKing** [comment]
Which option do you choose when installing the RHI? Just for you or for all users?

I haven't been able to reproduce problem where CyclesForRhino doesn't want to load on start, so perhaps you can give detailed steps that lead to the load failure for you?

It may very well be that something has changed with the Rhino Installer Engine that causes this to happen, there is not much I can do about that with the plug-in code. This plug-in is very simple, doesn't do much besides exposing what Rhino WIP already contains, namely the modal render engine of the Cycles integration.

**Comment by ilayshp** [comment]
Install - For me
You're right, maybe installer engine

anyway, after manually drop rhp in rhino, rhino re-register it. So all are ok

**Comment by jesterKing** [comment]
I'll keep an eye out for any installer engine issues reported to the Rhino issue tracker.

**Comment by ilayshp** [comment]
Thank you.
